version: "3.9"
name: eventure-hackatum

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.app.rule=Host(`eventure-sol.duckdns.org`)" # Replace with your domain
      - "traefik.http.routers.app.entrypoints=websecure"
      - "traefik.http.routers.app.tls.certresolver=lets-encrypt"
    environment:
      DATABASE_URL: "postgresql://postgres:hackatum@db:5432/eventure"
    depends_on:
      - db
    volumes:
      - .:/app
      - /app/node_modules

  db:
    image: postgres
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: hackatum
      POSTGRES_DB: eventure
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  traefik:
    image: traefik:v3.2
    container_name: traefik
    ports:
      - "80:80"
      - "443:443"    # HTTPS
    command:
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.lets-encrypt.acme.tlschallenge=true"
      - "--certificatesresolvers.lets-encrypt.acme.email=devstar0711@gcplab.me" # Replace with your email
      - "--certificatesresolvers.lets-encrypt.acme.storage=/letsencrypt/acme.json"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./letsencrypt:/letsencrypt

volumes:
  postgres_data:
  letsencrypt: